name: Jackdaw Installers for Windows

on:
  workflow_dispatch: # manually triggered
    inputs:
      release_type:
        type: choice
        options:
          - prerelease
          - test
        default: 'test'
  push:
    tags: 'v*'

jobs:
  build:
    runs-on: windows-2022
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v6
    - name: Build installers for Windows
      uses: actions/setup-node@v6
      with:
        node-version: 24.x

    - run: bash fix-installer-filenames.sh
      working-directory: app/build
      shell: bash
    - run: bash jackdaw-brand.sh
      working-directory: app/build
      shell: bash
    - name: OAuth2 secrets stub for CI
      run: cp OAuth2Secrets.local.example.ts OAuth2Secrets.user.ts
      working-directory: app/logic/Auth
      shell: bash
    - run: cd app; yarn install
    - run: cd lib; yarn install
    - run: cd desktop; yarn install
    - run: cd desktop/backend; yarn install
    - run: cd desktop; yarn run build:release:win
      if: github.event_name == 'push' || inputs.release_type == 'release'
      env: &build_env
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        # For Sentry source maps. Otherwise, vite build is out of memory
        NODE_OPTIONS: '--max-old-space-size=32768'
    - run: cd desktop; yarn run build:prerelease:win
      if: inputs.release_type == 'prerelease'
      env: *build_env
    - run: cd desktop; yarn run build && yarn electron-builder --win --config --publish never -c.publish=null -c.generateUpdatesFilesForAllChannels=false
      if: inputs.release_type == 'test'
      env: *build_env
    - name: Upload
      uses: actions/upload-artifact@v7
      with:
        name: Jackdaw Installers Windows
        path: |
          desktop/dist/*.exe
          desktop/dist/*.msi
